# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: especificacao.proto
"""Generated protocol buffer code."""

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x65specificacao.proto\x12\x05tftp2\"/\n\x03REQ\x12\r\n\x05\x66name\x18\x01 \x02(\t\x12\x19\n\x04mode\x18\x02 \x02(\x0e\x32\x0b.tftp2.Mode\"(\n\x04\x44\x41TA\x12\x0f\n\x07message\x18\x01 \x02(\x0c\x12\x0f\n\x07\x62lock_n\x18\x02 \x02(\r\"\x16\n\x03\x41\x43K\x12\x0f\n\x07\x62lock_n\x18\x01 \x02(\r\",\n\x05\x45rror\x12#\n\terrorcode\x18\x01 \x02(\x0e\x32\x10.tftp2.ErrorCode\"\x14\n\x04Path\x12\x0c\n\x04path\x18\x01 \x02(\t\".\n\x0cListResponse\x12\x1e\n\x05items\x18\x01 \x03(\x0b\x32\x0f.tftp2.ListItem\"M\n\x08ListItem\x12\x1b\n\x04\x66ile\x18\x01 \x01(\x0b\x32\x0b.tftp2.FILEH\x00\x12\x1a\n\x03\x64ir\x18\x02 \x01(\x0b\x32\x0b.tftp2.PathH\x00\x42\x08\n\x06\x61nswer\"%\n\x04\x46ILE\x12\x0c\n\x04nome\x18\x01 \x02(\t\x12\x0f\n\x07tamanho\x18\x02 \x02(\x05\",\n\x04MOVE\x12\x11\n\tnome_orig\x18\x01 \x02(\t\x12\x11\n\tnome_novo\x18\x02 \x01(\t\"\xa0\x02\n\x08Mensagem\x12\x19\n\x03rrq\x18\x01 \x01(\x0b\x32\n.tftp2.REQH\x00\x12\x19\n\x03wrq\x18\x02 \x01(\x0b\x32\n.tftp2.REQH\x00\x12\x1b\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x0b.tftp2.DATAH\x00\x12\x19\n\x03\x61\x63k\x18\x04 \x01(\x0b\x32\n.tftp2.ACKH\x00\x12\x1d\n\x05\x65rror\x18\x05 \x01(\x0b\x32\x0c.tftp2.ErrorH\x00\x12\x1b\n\x04list\x18\x06 \x01(\x0b\x32\x0b.tftp2.PathH\x00\x12(\n\tlist_resp\x18\x07 \x01(\x0b\x32\x13.tftp2.ListResponseH\x00\x12\x1c\n\x05mkdir\x18\x08 \x01(\x0b\x32\x0b.tftp2.PathH\x00\x12\x1b\n\x04move\x18\t \x01(\x0b\x32\x0b.tftp2.MOVEH\x00\x42\x05\n\x03msg*)\n\x04Mode\x12\x0c\n\x08netascii\x10\x01\x12\t\n\x05octet\x10\x02\x12\x08\n\x04mail\x10\x03*\x99\x01\n\tErrorCode\x12\x10\n\x0c\x46ileNotFound\x10\x01\x12\x13\n\x0f\x41\x63\x63\x65ssViolation\x10\x02\x12\x0c\n\x08\x44iskFull\x10\x03\x12\x14\n\x10IllegalOperation\x10\x04\x12\x0e\n\nUnknownTid\x10\x05\x12\x0e\n\nFileExists\x10\x06\x12\x12\n\x0eUnknownSession\x10\x07\x12\r\n\tUndefined\x10\x08')

_MODE = DESCRIPTOR.enum_types_by_name['Mode']
Mode = enum_type_wrapper.EnumTypeWrapper(_MODE)
_ERRORCODE = DESCRIPTOR.enum_types_by_name['ErrorCode']
ErrorCode = enum_type_wrapper.EnumTypeWrapper(_ERRORCODE)
netascii = 1
octet = 2
mail = 3
FileNotFound = 1
AccessViolation = 2
DiskFull = 3
IllegalOperation = 4
UnknownTid = 5
FileExists = 6
UnknownSession = 7
Undefined = 8


_REQ = DESCRIPTOR.message_types_by_name['REQ']
_DATA = DESCRIPTOR.message_types_by_name['DATA']
_ACK = DESCRIPTOR.message_types_by_name['ACK']
_ERROR = DESCRIPTOR.message_types_by_name['Error']
_PATH = DESCRIPTOR.message_types_by_name['Path']
_LISTRESPONSE = DESCRIPTOR.message_types_by_name['ListResponse']
_LISTITEM = DESCRIPTOR.message_types_by_name['ListItem']
_FILE = DESCRIPTOR.message_types_by_name['FILE']
_MOVE = DESCRIPTOR.message_types_by_name['MOVE']
_MENSAGEM = DESCRIPTOR.message_types_by_name['Mensagem']
REQ = _reflection.GeneratedProtocolMessageType('REQ', (_message.Message,), {
  'DESCRIPTOR' : _REQ,
  '__module__' : 'especificacao_pb2'
  # @@protoc_insertion_point(class_scope:tftp2.REQ)
  })
_sym_db.RegisterMessage(REQ)

DATA = _reflection.GeneratedProtocolMessageType('DATA', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'especificacao_pb2'
  # @@protoc_insertion_point(class_scope:tftp2.DATA)
  })
_sym_db.RegisterMessage(DATA)

ACK = _reflection.GeneratedProtocolMessageType('ACK', (_message.Message,), {
  'DESCRIPTOR' : _ACK,
  '__module__' : 'especificacao_pb2'
  # @@protoc_insertion_point(class_scope:tftp2.ACK)
  })
_sym_db.RegisterMessage(ACK)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
  'DESCRIPTOR' : _ERROR,
  '__module__' : 'especificacao_pb2'
  # @@protoc_insertion_point(class_scope:tftp2.Error)
  })
_sym_db.RegisterMessage(Error)

Path = _reflection.GeneratedProtocolMessageType('Path', (_message.Message,), {
  'DESCRIPTOR' : _PATH,
  '__module__' : 'especificacao_pb2'
  # @@protoc_insertion_point(class_scope:tftp2.Path)
  })
_sym_db.RegisterMessage(Path)

ListResponse = _reflection.GeneratedProtocolMessageType('ListResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTRESPONSE,
  '__module__' : 'especificacao_pb2'
  # @@protoc_insertion_point(class_scope:tftp2.ListResponse)
  })
_sym_db.RegisterMessage(ListResponse)

ListItem = _reflection.GeneratedProtocolMessageType('ListItem', (_message.Message,), {
  'DESCRIPTOR' : _LISTITEM,
  '__module__' : 'especificacao_pb2'
  # @@protoc_insertion_point(class_scope:tftp2.ListItem)
  })
_sym_db.RegisterMessage(ListItem)

FILE = _reflection.GeneratedProtocolMessageType('FILE', (_message.Message,), {
  'DESCRIPTOR' : _FILE,
  '__module__' : 'especificacao_pb2'
  # @@protoc_insertion_point(class_scope:tftp2.FILE)
  })
_sym_db.RegisterMessage(FILE)

MOVE = _reflection.GeneratedProtocolMessageType('MOVE', (_message.Message,), {
  'DESCRIPTOR' : _MOVE,
  '__module__' : 'especificacao_pb2'
  # @@protoc_insertion_point(class_scope:tftp2.MOVE)
  })
_sym_db.RegisterMessage(MOVE)

Mensagem = _reflection.GeneratedProtocolMessageType('Mensagem', (_message.Message,), {
  'DESCRIPTOR' : _MENSAGEM,
  '__module__' : 'especificacao_pb2'
  # @@protoc_insertion_point(class_scope:tftp2.Mensagem)
  })
_sym_db.RegisterMessage(Mensagem)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODE._serialized_start=716
  _MODE._serialized_end=757
  _ERRORCODE._serialized_start=760
  _ERRORCODE._serialized_end=913
  _REQ._serialized_start=30
  _REQ._serialized_end=77
  _DATA._serialized_start=79
  _DATA._serialized_end=119
  _ACK._serialized_start=121
  _ACK._serialized_end=143
  _ERROR._serialized_start=145
  _ERROR._serialized_end=189
  _PATH._serialized_start=191
  _PATH._serialized_end=211
  _LISTRESPONSE._serialized_start=213
  _LISTRESPONSE._serialized_end=259
  _LISTITEM._serialized_start=261
  _LISTITEM._serialized_end=338
  _FILE._serialized_start=340
  _FILE._serialized_end=377
  _MOVE._serialized_start=379
  _MOVE._serialized_end=423
  _MENSAGEM._serialized_start=426
  _MENSAGEM._serialized_end=714
# @@protoc_insertion_point(module_scope)
